In [1]:
import pandas as pd
import numpy as np

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

In [2]:
app = Flask(__name__)

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:1234@localhost:5432/Section6_P1_Recipe'
# app.config['SQLALCHEMY_BINDS'] = {'other_schema' : }
app.config['SECRET_KEY'] = "key"

db = SQLAlchemy(app)
db.init_app(app)
db.Model.metadata.reflect(db.engine)

In [3]:
conn = db.engine.connect()

In [4]:
db.Model.metadata

MetaData()

In [5]:
db.Model.metadata.tables

FacadeDict({'raw_recipes_csv': Table('raw_recipes_csv', MetaData(), Column('name', TEXT(), table=<raw_recipes_csv>), Column('id', INTEGER(), table=<raw_recipes_csv>, primary_key=True, nullable=False), Column('minutes', INTEGER(), table=<raw_recipes_csv>), Column('contributor_id', INTEGER(), table=<raw_recipes_csv>), Column('submitted', TEXT(), table=<raw_recipes_csv>), Column('tags', TEXT(), table=<raw_recipes_csv>), Column('nutrition', TEXT(), table=<raw_recipes_csv>), Column('n_steps', INTEGER(), table=<raw_recipes_csv>), Column('steps', TEXT(), table=<raw_recipes_csv>), Column('description', TEXT(), table=<raw_recipes_csv>), Column('ingredients', TEXT(), table=<raw_recipes_csv>), Column('n_ingredients', INTEGER(), table=<raw_recipes_csv>), schema=None), 'pp_users_csv': Table('pp_users_csv', MetaData(), Column('u', INTEGER(), table=<pp_users_csv>, primary_key=True, nullable=False), Column('techniques', VARCHAR(length=259), table=<pp_users_csv>), Column('items', VARCHAR(length=47485),

In [6]:
recipes = pd.read_sql_table("pp_recipes", db.engine)
recipes.head()

id  calorie_level                                              in_id  \
0  230049              1  [1257, 840, 3446, 2148, 5010, 4863, 1254, 2451...   
1  451135              0                                         [117, 510]   
2  167163              0                            [840, 7899, 5893, 6270]   
3  276949              1  [3203, 2844, 393, 4284, 1257, 840, 1124, 5006,...   
4  389419              0  [2777, 553, 2007, 4096, 1257, 1329, 3486, 6265...   

   ingredient_id1  ingredient_id2  ingredient_id3  ingredient_id4  \
0            1257           840.0          3446.0          2148.0   
1             117           510.0             NaN             NaN   
2             840          7899.0          5893.0          6270.0   
3            3203          2844.0           393.0          4284.0   
4            2777           553.0          2007.0          4096.0   

   ingredient_id5  ingredient_id6  ingredient_id7  ingredient_id8  \
0          5010.0          4863.0          1254.0          2451.0   
1             NaN             NaN             NaN             NaN   
2             NaN             NaN             NaN             NaN   
3          1257.0           840.0          1124.0          5006.0   
4          1257.0          1329.0          3486.0          6265.0   

   ingredient_id9  ingredient_id10  
0          7705.0              NaN  
1             NaN              NaN  
2             NaN              NaN  
3          5010.0           3184.0  
4          3418.0           5010.0

In [7]:
len(recipes)

30562

In [8]:
interactions = pd.read_sql_table("raw_interactions2_csv", db.engine)
interactions.head()

user_id  recipe_id        date  rating  \
0    13483     120964  2005-05-15       5   
1     6357      98783  2004-09-01       5   
2    14112      98783  2006-01-04       5   
3    13483      98783  2008-04-27       5   
4     9869      20823  2002-08-05       5   

                                              review  temp_id  
0  Well these are just gems.  They are so much be...      575  
1  This was incredibly truly so yummy that my dad...      708  
2  This fudge is delicious!  I have never made fu...      718  
3  Just a very easy yet excellent fudge to make. ...      752  
4  Very tasty soup. My family liked this a lot, I...      918

In [9]:
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Input, Embedding, Flatten, Dot, Dense, Concatenate
from tensorflow.keras.models import Model

from sklearn.preprocessing import LabelEncoder

# import matplotlib
# import warnings
# warnings.filterwarnings('ignore')
# %matplotlib inline

In [10]:
user_enc = LabelEncoder()
interactions['user'] = user_enc.fit_transform(interactions['user_id'].values)
n_users = interactions['user'].nunique()
item_enc = LabelEncoder()
interactions['recipe'] = item_enc.fit_transform(interactions['recipe_id'].values)
n_movies = interactions['recipe'].nunique()
interactions['rating'] = interactions['rating'].values.astype(np.float32)
min_rating = min(interactions['rating'])
max_rating = max(interactions['rating'])
n_users, n_movies, min_rating, max_rating

(496, 2253, 0.0, 5.0)

In [11]:
n_movies

2253

In [12]:
n_recipes = len(recipes)
n_recipes

30562

In [13]:
X = interactions[['user', 'recipe']].values
y = interactions['rating'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2918, 2), (325, 2), (2918,), (325,))

In [14]:
n_factors = 5000
X_train_array = [X_train[:, 0], X_train[:, 1]]
X_test_array = [X_test[:, 0], X_test[:, 1]]

In [15]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Reshape, Dot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2

In [16]:
from tensorflow.keras.layers import Add, Activation, Lambda
class EmbeddingLayer:
    def __init__(self, n_items, n_factors):
        self.n_items = n_items
        self.n_factors = n_factors
    
    def __call__(self, x):
        x = Embedding(self.n_items, self.n_factors, embeddings_initializer='he_normal',
                      embeddings_regularizer=l2(1e-6))(x)
        x = Reshape((self.n_factors,))(x)
        return x

In [17]:
from tensorflow.keras.layers import Concatenate, Dense, Dropout
def Recommender_DNN(n_users, n_movies, n_factors, min_rating, max_rating):
    user = Input(shape=(1,))
    u = EmbeddingLayer(n_users, n_factors)(user)
    
    movie = Input(shape=(1,))
    m = EmbeddingLayer(n_movies, n_factors)(movie)
    
    x = Concatenate()([u, m])
    x = Dropout(0.05)(x)
    
    x = Dense(128, kernel_initializer='he_normal')(x)
    x = Activation('relu')(x)
    x = Dropout(0.5)(x)
    
    x = Dense(1, kernel_initializer='he_normal')(x)
    x = Activation('sigmoid')(x)
    x = Lambda(lambda x: x * (max_rating - min_rating) + min_rating)(x)
    model = Model(inputs=[user, movie], outputs=x)
    opt = Adam(lr=0.001)
    model.compile(loss='mean_squared_error', optimizer=opt)
    return model

In [18]:
model_DNN = Recommender_DNN(n_users, n_movies+1, n_factors+1, min_rating, max_rating)
model_DNN.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 1, 30563)     15159248    input_1[0][0]                    
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 1, 30563)     68889002    input_2[0][0]                    
______________________________________________________________________________________________

C:\Users\tkryu\anaconda3\envs\Section3\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [19]:
from tensorflow.keras.utils import plot_model
plot_model(model_DNN, to_file='./DNN_model.png', show_shapes=True, show_layer_names=True, dpi=70)

('You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) ', 'for plot_model/model_to_dot to work.')


In [20]:
history = model_DNN.fit(x=X_train_array, y=y_train, batch_size=64, epochs=5,
                    verbose=1, validation_data=(X_test_array, y_test))

Epoch 1/5
46/46 [==============================] - 27s 555ms/step - loss: 1.7033 - val_loss: 1.0132
Epoch 2/5
46/46 [==============================] - 25s 534ms/step - loss: 0.8776 - val_loss: 1.0044
Epoch 3/5
46/46 [==============================] - 24s 527ms/step - loss: 0.7381 - val_loss: 1.0650
Epoch 4/5
46/46 [==============================] - 25s 552ms/step - loss: 0.6338 - val_loss: 0.8698
Epoch 5/5
46/46 [==============================] - 24s 527ms/step - loss: 0.4878 - val_loss: 0.9472


In [21]:
predictions = model_DNN.predict(X_test_array)
[print(predictions[i], y_test[i]) for i in range(0,10)]

[5.] 5.0
[4.8819976] 4.0
[2.8238301] 5.0
[4.985985] 5.0
[0.91506666] 5.0
[4.982811] 5.0
[4.982856] 4.0
[4.952835] 5.0
[4.962207] 5.0
[4.8977685] 5.0


[None, None, None, None, None, None, None, None, None, None]

In [22]:
# user_ids = interactions['user'].unique().tolist()
# recipe_ids = interactions['recipe'].unique().tolist()

# user__id = interactions.user_id.sample(1).iloc[0]

# recipe_rated = interactions[interactions.user_id == user__id]
# recipe_not_rated = recipes[
#     ~recipes['id'].isin(recipe_rated.recipe_id.values)
# ]['id']

In [65]:
user_ids = interactions['user_id'].unique().tolist()
recipe_ids = interactions['recipe_id'].unique().tolist()

sample_id = interactions.user_id.sample(1).iloc[0]

recipe_rated = interactions[interactions.user_id == sample_id]
recipe_not_rated = recipes[
    ~recipes['id'].isin(recipe_rated.recipe_id.values)
]['id']

In [38]:
recipe_not_rated

0        230049
1        451135
2        167163
3        276949
4        389419
          ...  
30557    455789
30558     18736
30559    262291
30560    348366
30561    215775
Name: id, Length: 30511, dtype: int64

In [57]:
interactions['recipe'].unique()

array([1479, 1295,  364, ...,  334,  840, 1638], dtype=int64)

In [60]:
len(interactions)

3243

In [94]:
interactions['recipe'].unique()

array([1479, 1295,  364, ...,  334,  840, 1638], dtype=int64)

In [59]:
interactions[interactions.recipe.isin(interactions['recipe'].unique())]

user_id  recipe_id        date  rating  \
0       13483     120964  2005-05-15     5.0   
1        6357      98783  2004-09-01     5.0   
2       14112      98783  2006-01-04     5.0   
3       13483      98783  2008-04-27     5.0   
4        9869      20823  2002-08-05     5.0   
...       ...        ...         ...     ...   
3238    15851      52360  2003-05-24     4.0   
3239     9869      52360  2003-02-02     5.0   
3240    20480     152441  2007-07-07     5.0   
3241    13483     152441  2007-10-17     5.0   
3242     8688     152441  2008-01-18     5.0   

                                                 review  temp_id  user  recipe  
0     Well these are just gems.  They are so much be...      575   192    1479  
1     This was incredibly truly so yummy that my dad...      708    69    1295  
2     This fudge is delicious!  I have never made fu...      718   212    1295  
3     Just a very easy yet excellent fudge to make. ...      752   192    1295  
4     Very tasty soup. My family liked this a lot, I...      918   137     364  
...                                                 ...      ...   ...     ...  
3238  This was really yummy!  I  did add some cilant...   621428   255     840  
3239  Very tasty rice dish, I made this to go along ...   621500   137     840  
3240  I served these carrots with my meal last night...   621663   367    1638  
3241  Excellent veggie dish.  I made the dish a day ...   621678   192    1638  
3242  Delicious simple and easy to put on your table...   621686   114    1638  

[3243 rows x 8 columns]

In [67]:
recipe_not_rated2 = [[i] for i in recipe_not_rated]
recipe_not_rated2[0][0]

230049

In [68]:
len(recipe_not_rated2)

30489

In [69]:
user_recipe_array = np.hstack(
    ([[user__id]] * len(recipe_not_rated2), recipe_not_rated2)
)

user_recipe_array

array([[ 13483, 230049],
       [ 13483, 451135],
       [ 13483, 167163],
       ...,
       [ 13483, 262291],
       [ 13483, 348366],
       [ 13483, 215775]], dtype=int64)

In [70]:
arr = [user_recipe_array[:,0], user_recipe_array[:,1]]
arr

[array([13483, 13483, 13483, ..., 13483, 13483, 13483], dtype=int64),
 array([230049, 451135, 167163, ..., 262291, 348366, 215775], dtype=int64)]

In [71]:
len(arr[0])

30489

In [72]:
recipe_rated.recipe_id.iloc[1]

88116

In [73]:
len(recipes)

30562

In [74]:
len(recipes.id.unique())

30562

In [75]:
recipes[recipes.id == 188991]

Empty DataFrame
Columns: [id, calorie_level, in_id, ingredient_id1, ingredient_id2, ingredient_id3, ingredient_id4, ingredient_id5, ingredient_id6, ingredient_id7, ingredient_id8, ingredient_id9, ingredient_id10]
Index: []

In [76]:
# for i in range(len(recipe_rated)):
#     if recipe_rated.recipe_id.iloc[i] not in 

In [77]:
pred = model_DNN.predict(arr)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[31,0] = 13483 is not in [0, 496)
	 [[node model/embedding/embedding_lookup (defined at <ipython-input-21-b291dd62eb25>:1) ]]
  (1) Invalid argument:  indices[31,0] = 13483 is not in [0, 496)
	 [[node model/embedding/embedding_lookup (defined at <ipython-input-21-b291dd62eb25>:1) ]]
	 [[model/embedding_1/embedding_lookup/_12]]
0 successful operations.
0 derived errors ignored. [Op:__inference_predict_function_1603]

Errors may have originated from an input operation.
Input Source operations connected to node model/embedding/embedding_lookup:
 model/embedding/embedding_lookup/1557 (defined at C:\Users\tkryu\anaconda3\envs\Section3\lib\contextlib.py:113)

Input Source operations connected to node model/embedding/embedding_lookup:
 model/embedding/embedding_lookup/1557 (defined at C:\Users\tkryu\anaconda3\envs\Section3\lib\contextlib.py:113)

Function call stack:
predict_function -> predict_function


In [83]:
interactions

user_id  recipe_id        date  rating  \
0       13483     120964  2005-05-15     5.0   
1        6357      98783  2004-09-01     5.0   
2       14112      98783  2006-01-04     5.0   
3       13483      98783  2008-04-27     5.0   
4        9869      20823  2002-08-05     5.0   
...       ...        ...         ...     ...   
3238    15851      52360  2003-05-24     4.0   
3239     9869      52360  2003-02-02     5.0   
3240    20480     152441  2007-07-07     5.0   
3241    13483     152441  2007-10-17     5.0   
3242     8688     152441  2008-01-18     5.0   

                                                 review  temp_id  user  recipe  
0     Well these are just gems.  They are so much be...      575   192    1479  
1     This was incredibly truly so yummy that my dad...      708    69    1295  
2     This fudge is delicious!  I have never made fu...      718   212    1295  
3     Just a very easy yet excellent fudge to make. ...      752   192    1295  
4     Very tasty soup. My family liked this a lot, I...      918   137     364  
...                                                 ...      ...   ...     ...  
3238  This was really yummy!  I  did add some cilant...   621428   255     840  
3239  Very tasty rice dish, I made this to go along ...   621500   137     840  
3240  I served these carrots with my meal last night...   621663   367    1638  
3241  Excellent veggie dish.  I made the dish a day ...   621678   192    1638  
3242  Delicious simple and easy to put on your table...   621686   114    1638  

[3243 rows x 8 columns]

In [108]:
sample_id2

28

In [109]:
recipe_rated2

user_id  recipe_id        date  rating  \
321      4500     244919  2008-05-05     5.0   
722      4500     269785  2008-01-22     5.0   
1559     4500     255399  2007-09-28     5.0   
1854     4500       9372  2008-07-29     5.0   
1892     4500     275888  2008-03-31     5.0   
2127     4500     217021  2007-10-22     5.0   
2249     4500     164395  2009-01-10     5.0   
2258     4500     267834  2008-03-10     5.0   
2273     4500     173106  2009-01-11     5.0   
2400     4500     257065  2008-07-03     5.0   
2716     4500     229275  2010-05-30     5.0   
2916     4500     141409  2009-01-12     5.0   
3036     4500       9982  2007-09-26     4.0   

                                                 review  temp_id  user  recipe  
321   Great method for candying violets. The only ch...    58391    28    1936  
722   Very refreshing indeed! I halved the vodka and...   129336    28    2000  
1559  I have this Woman's World from 11/15/05 saved!...   282402    28    1965  
1854  I have made this twice and my family has raved...   340560    28     107  
1892  This makes a thick and hearty soup with just t...   349670    28    2007  
2127  Alice Chicken is my favorite dish from Outback...   394983    28    1876  
2249  This was fabulous! It wasn't light in flavor!!...   424531    28    1690  
2258  This was fabulous! The potatoes are perfectly ...   425836    28    1997  
2273  Delicious! Hearty enough for a lumberjack! The...   429282    28    1718  
2400  Fabulous! This is easy enough to make for an e...   457876    28    1969  
2716  Simple to make and delicious! Made with alread...   511226    28    1906  
2916  I made it exactly as directed and it was aweso...   555673    28    1567  
3036  Great soup! I used stock instead of the bouill...   578217    28     123

In [88]:
recipe_not_rated_v2

0       1479
1       1295
2       1295
3       1295
4        364
        ... 
3238     840
3239     840
3240    1638
3241    1638
3242    1638
Name: recipe, Length: 3143, dtype: int64

In [100]:
len(recipe_not_rated_v2.unique())

2203

In [105]:
recipe_not_rated_v2_2 = [[i] for i in recipe_not_rated_v2.unique()]
len(recipe_not_rated_v2_2)

2203

In [96]:
recipe_not_rated_v2.unique()

array([1479, 1295,  364, ...,  334,  840, 1638], dtype=int64)

In [107]:
arr_v2

[array([13483, 13483, 13483, ..., 13483, 13483, 13483], dtype=int64),
 array([1479, 1295,  364, ...,  334,  840, 1638], dtype=int64)]

In [110]:
user_ids2 = interactions['user_id'].unique().tolist()
recipe_ids2 = interactions['recipe_id'].unique().tolist()

sample_id2 = interactions.user.sample(1).iloc[0]

recipe_rated2 = interactions[interactions.user == sample_id2]

recipe_not_rated_v2 = interactions[
    ~interactions['recipe'].isin(recipe_rated2.recipe.values)
]['recipe']

recipe_not_rated_v2_2 = [[i] for i in recipe_not_rated_v2.unique()]

user_recipe_array_v2 = np.hstack(
    ([[sample_id2]] * len(recipe_not_rated_v2_2), recipe_not_rated_v2_2)
)

arr_v2 = [user_recipe_array_v2[:,0], user_recipe_array_v2[:,1]]

pred = model_DNN.predict(arr_v2)

In [111]:
pred

array([[4.981987 ],
       [4.9989586],
       [4.9828615],
       ...,
       [4.999384 ],
       [4.587443 ],
       [4.998692 ]], dtype=float32)